

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: dating_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Go сервис регистрации
  register-service:
    build: ./register-service
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: dating_app
      PORT: 8080
    depends_on:
      - postgres

  # Go сервис входа
  entrance-service:
    build: ./entrance-service
    ports:
      - "8081:8081"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: dating_app
      PORT: 8081
      JWT_SECRET: your-super-secure-jwt-secret-key-here
    depends_on:
      - postgres

  # Nest.js Gateway
  gateway:
    build: ./gateway
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
    depends_on:
      - register-service
      - entrance-service

volumes:
  postgres_data: